import {
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconBold,
  IconBraces,
  IconCheck,
  IconChecklist,
  IconChevronDown,
  IconCode,
  IconCopy,
  IconFileText,
  IconGripVertical,
  IconHeading,
  IconItalic,
  IconLink,
  IconList,
  IconListNumbers,
  IconMinus,
  IconPhoto,
  IconQuote,
  IconSearch,
  IconSourceCode,
  IconStrikethrough,
  IconTable,
  IconTrash,
  IconTypography,
  IconUnderline,
  IconUnlink,
} from "@tabler/icons-react";

import type { BlockEditorIcons } from "./icons";
import { DEFAULT_LANGUAGE_ICONS } from "./language-icons";

// Tabler Icons preset for BlockEditor ("iconLibrary": "tabler", @tabler/icons-react).
export const DEFAULT_ICONS: BlockEditorIcons = {
  alignCenterIcon: <IconAlignCenter />,
  alignLeftIcon: <IconAlignLeft />,
  alignRightIcon: <IconAlignRight />,
  boldIcon: <IconBold />,
  checkIcon: <IconCheck />,
  codeBlockLanguageIcon: <IconBraces />,
  codeIcon: <IconCode />,
  copyIcon: <IconCopy />,
  deleteIcon: <IconTrash />,
  dragHandleIcon: (
    <IconGripVertical className="block-editor-drag-handle-icon" />
  ),
  dropdownArrowIcon: <IconChevronDown size={12} />,
  fallbackIcon: <IconFileText />,
  italicIcon: <IconItalic />,
  languageIcons: DEFAULT_LANGUAGE_ICONS,
  linkIcon: <IconLink />,
  searchIcon: <IconSearch size={14} />,
  slashBlockquoteIcon: <IconQuote />,
  slashBulletListIcon: <IconList />,
  slashCodeBlockIcon: <IconSourceCode />,
  slashDividerIcon: <IconMinus />,
  slashHeadingIcon: <IconHeading />,
  slashImageIcon: <IconPhoto />,
  slashOrderedListIcon: <IconListNumbers />,
  slashTableIcon: <IconTable />,
  slashTaskListIcon: <IconChecklist />,
  slashTextIcon: <IconTypography />,
  strikethroughIcon: <IconStrikethrough />,
  underlineIcon: <IconUnderline />,
  unlinkIcon: <IconUnlink />,
};
